import { useEffect, useState } from "react";
import axios from "axios";
import toast from "react-hot-toast";
import DashboardLayout from "../../components/dashboard/DashboardLayout";

const API = "https://smart-society-backend-delta.vercel.app/resident";
const config = () => ({ headers: { Authorization: `Bearer ${localStorage.getItem("token")}` } });

export default function ResidentVisitorRequests() {
  const [settings, setSettings] = useState({ visitorRequestsEnabled: true, visitorAvailabilityMode: "available", visitorUnavailableUntil: "", visitingHours: { start: "09:00", end: "20:00" } });
  const [requests, setRequests] = useState([]);
  const load = async () => { try { const [a, b] = await Promise.all([axios.get(`${API}/visitor-settings`, config()), axios.get(`${API}/visitor-requests`, config())]); setSettings({ ...a.data.data, visitorUnavailableUntil: a.data.data.visitorUnavailableUntil?.slice(0,16) || "" }); setRequests(b.data.data || []); } catch { toast.error("Could not load visitor requests"); } };
  useEffect(()=>{load();},[]);
  const save = async (e) => { e.preventDefault(); try { await axios.put(`${API}/visitor-settings`, settings, config()); toast.success("Availability saved"); load(); } catch (err) { toast.error(err.response?.data?.message || "Could not save availability"); } };
  const respond = async (id, action) => { try { await axios.patch(`${API}/visitor-requests/${id}`, { action }, config()); toast.success(`Request ${action}d`); load(); } catch (err) { toast.error(err.response?.data?.message || "Could not update request"); } };
  return <DashboardLayout role="resident"><div className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-widest text-[#9b7740]">Resident Portal</p><h1 className="text-2xl font-black text-[#32143b]">Visitor requests</h1></div><form onSubmit={save} className="border bg-white p-5"><h2 className="font-bold">Visitor availability</h2><label className="mt-3 block"><input type="checkbox" checked={settings.visitorRequestsEnabled} onChange={(e)=>setSettings({...settings,visitorRequestsEnabled:e.target.checked})}/> <span className="ml-2">Allow visitor requests</span></label><select value={settings.visitorAvailabilityMode} onChange={(e)=>setSettings({...settings,visitorAvailabilityMode:e.target.value})} className="mt-3 h-10 border px-3"><option value="available">Available now</option><option value="unavailable">Unavailable</option><option value="scheduled">Custom visiting hours</option></select>{settings.visitorAvailabilityMode === "unavailable" && <input type="datetime-local" value={settings.visitorUnavailableUntil} onChange={(e)=>setSettings({...settings,visitorUnavailableUntil:e.target.value})} className="ml-3 h-10 border px-3"/>}<button className="ml-3 bg-[#32143b] px-4 py-2 text-sm font-bold text-white">Save</button></form><section className="border bg-white p-5"><h2 className="font-bold">Incoming requests</h2>{requests.map((item)=><div key={item._id} className="mt-3 flex flex-wrap items-center justify-between gap-3 border p-3"><div><b>{item.visitorName}</b><p className="text-sm">{item.phone} · {item.purpose}</p><p className="text-sm font-bold text-[#9b7740]">{item.status}</p></div>{item.status === "Pending" && <div className="flex gap-2"><button onClick={()=>respond(item._id,"approve")} className="bg-green-700 px-3 py-2 text-xs font-bold text-white">Approve</button><button onClick={()=>respond(item._id,"reject")} className="bg-red-700 px-3 py-2 text-xs font-bold text-white">Reject</button></div>}</div>)}{!requests.length && <p className="mt-3 text-sm text-[#756b78]">No incoming requests.</p>}</section></div></DashboardLayout>;
}
