import { useState } from "react";
import axios from "axios";
import toast from "react-hot-toast";
import { CalendarPlus, Search } from "lucide-react";
import DashboardLayout from "../../components/dashboard/DashboardLayout";
import VisitorPageHeader from "../../components/visitor/VisitorPageHeader";

const API = "https://smart-society-backend-delta.vercel.app/visitor";
const config = () => ({ headers: { Authorization: `Bearer ${localStorage.getItem("token")}` } });

export default function VisitorRequest() {
  const [flatNo, setFlatNo] = useState("");
  const [resident, setResident] = useState(null);
  const [form, setForm] = useState({ purpose: "", visitorType: "Guest", visitDate: "", visitStartTime: "", visitEndTime: "" });
  const find = async () => { try { setResident((await axios.get(`${API}/residents?flatNo=${encodeURIComponent(flatNo)}`, config())).data.data); } catch (e) { setResident(null); toast.error(e.response?.data?.message || "Resident not found"); } };
  const submit = async (e) => { e.preventDefault(); try { const r = await axios.post(`${API}/requests`, { ...form, residentId: resident?._id, visitStartTime: `${form.visitDate}T${form.visitStartTime}`, visitEndTime: `${form.visitDate}T${form.visitEndTime}` }, config()); toast.success(r.data.message); } catch (e) { toast.error(e.response?.data?.message || "Could not send request"); } };
  return <DashboardLayout role="visitor"><div className="max-w-4xl"><VisitorPageHeader title="Request a Visit" description="Find a resident and send a secure visit request." icon={CalendarPlus}/><section className="overflow-hidden border border-[#e2d9df] bg-white"><div className="flex items-center gap-3 border-b border-[#e2d9df] px-5 py-4"><Search size={17} className="text-[#9b7740]"/><div><h2 className="text-[13px] font-bold text-[#32143b]">Resident Lookup</h2><p className="text-[9.5px] text-[#8b778e]">The resident controls whether requests can be accepted.</p></div></div><form onSubmit={submit} className="space-y-5 p-5"><div><label className="text-[10px] font-bold uppercase tracking-wide text-[#756b78]">Resident flat number</label><div className="mt-2 flex gap-2"><input value={flatNo} onChange={e => setFlatNo(e.target.value)} className="h-11 flex-1 border border-[#e2d9df] px-3 text-sm" placeholder="e.g. A-101"/><button onClick={find} type="button" className="bg-[#32143b] px-5 text-sm font-bold text-white">Find resident</button></div></div>{resident && <div className={`border p-4 text-sm ${resident.acceptingRequests ? "border-green-200 bg-green-50" : "border-red-200 bg-red-50"}`}><b>{resident.name}</b> · Flat {resident.flatNo}<p className="mt-1">{resident.availabilityMessage}</p></div>}<div className="grid gap-4 border-t border-[#eee8ed] pt-5"><input required placeholder="Purpose of visit" onChange={e => setForm({ ...form, purpose: e.target.value })} className="h-11 border border-[#e2d9df] px-3 text-sm"/><select onChange={e => setForm({ ...form, visitorType: e.target.value })} className="h-11 border border-[#e2d9df] px-3 text-sm"><option>Guest</option><option>Delivery</option><option>Cab</option><option>Vendor</option></select><input required type="date" onChange={e => setForm({ ...form, visitDate: e.target.value })} className="h-11 border border-[#e2d9df] px-3 text-sm"/><div className="grid grid-cols-2 gap-4"><input required type="time" onChange={e => setForm({ ...form, visitStartTime: e.target.value })} className="h-11 border border-[#e2d9df] px-3 text-sm"/><input required type="time" onChange={e => setForm({ ...form, visitEndTime: e.target.value })} className="h-11 border border-[#e2d9df] px-3 text-sm"/></div><button disabled={!resident?.acceptingRequests} className="h-11 bg-[#9b7740] text-sm font-bold text-white disabled:opacity-50">Send visit request</button></div></form></section></div></DashboardLayout>;
}
