import { useEffect, useState } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import QRCode from "qrcode";
import toast from "react-hot-toast";
import DashboardLayout from "../../components/dashboard/DashboardLayout";
const API="https://smart-society-backend-delta.vercel.app/visitor"; const config=()=>({headers:{Authorization:`Bearer ${localStorage.getItem("token")}`}});
const qrUrl = (key) => `https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(key)}`;
const download = async (pass) => { try { const qr = await QRCode.toDataURL(pass.gateKey, { width: 300, margin: 2 }); const pdf = new jsPDF(); const width = pdf.internal.pageSize.getWidth(); pdf.setFillColor(50,20,59); pdf.rect(0,0,width,32,"F"); pdf.setTextColor(255,255,255); pdf.setFontSize(20); pdf.setFont("helvetica","bold"); pdf.text("SmartSociety",20,20); pdf.setFontSize(9); pdf.text("DIGITAL VISITOR PASS",width-20,20,{align:"right"}); pdf.setTextColor(50,20,59); pdf.setFontSize(17); pdf.text("Approved Visitor Pass",20,48); pdf.addImage(qr,"PNG",width-78,60,55,55); let y=68; [["Visitor",pass.visitorName],["Resident",pass.resident?.name],["Flat",pass.flatNo],["Visit",new Date(pass.visitStartTime).toLocaleString()],["Purpose",pass.purpose]].forEach(([a,b])=>{pdf.setFontSize(10);pdf.setFont("helvetica","bold");pdf.text(a,20,y);pdf.setFont("helvetica","normal");pdf.text(String(b||"-"),58,y);y+=12}); pdf.setFillColor(247,243,237);pdf.rect(20,135,width-40,30,"F");pdf.setFont("helvetica","bold");pdf.setFontSize(10);pdf.text("GATE KEY",width/2,146,{align:"center"});pdf.setFontSize(20);pdf.text(pass.gateKey,width/2,159,{align:"center"});pdf.setFontSize(9);pdf.setFont("helvetica","normal");pdf.text("Show this QR code or gate key to society security at entry.",20,180);pdf.save(`SmartSociety-Pass-${pass.gateKey}.pdf`);toast.success("Visitor pass downloaded"); } catch { toast.error("Could not generate the PDF pass"); } };
export default function VisitorPasses(){const[requests,setRequests]=useState([]);useEffect(()=>{axios.get(`${API}/requests`,config()).then(r=>setRequests(r.data.data||[]))},[]);return <DashboardLayout role="visitor"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#9b7740]">Visitor Portal</p><h1 className="mt-2 text-2xl font-extrabold text-[#32143b]">My visit passes</h1><section className="mt-6 overflow-hidden border border-[#e2d9df] bg-white"><div className="border-b px-5 py-4"><h2 className="font-bold text-[#32143b]">Request history</h2><p className="mt-1 text-xs text-[#8b778e]">Approved passes include a QR code and downloadable PDF for gate entry.</p></div><div className="divide-y">{requests.map(r=><div key={r._id} className="p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><b className="text-[#32143b]">{r.resident?.name || "Resident"} · Flat {r.resident?.flatNo}</b><p className="mt-1 text-sm text-[#756b78]">{r.purpose} · {new Date(r.visitStartTime).toLocaleString()}</p></div><div className="text-left sm:text-right"><p className="font-bold text-[#9b7740]">{r.status}</p>{r.status==="Approved"&&<p className="mt-1 text-sm text-[#32143b]">Gate key: <b>{r.gateKey}</b></p>}</div></div>{r.status==="Approved"&&<div className="mt-4 flex flex-col items-start gap-4 border-t pt-4 sm:flex-row sm:items-center"><img src={qrUrl(r.gateKey)} alt="Visitor pass QR code" className="h-28 w-28 border p-1"/><div><p className="text-sm font-bold text-[#32143b]">Digital gate pass</p><p className="mt-1 text-xs text-[#8b778e]">Show this QR code or your gate key to the security guard.</p><button onClick={()=>download(r)} className="mt-3 bg-[#32143b] px-4 py-2 text-xs font-bold text-white">Download PDF pass</button></div></div>}</div>)}{!requests.length&&<p className="p-5 text-sm text-[#8b778e]">No visit requests yet.</p>}</div></section></div></DashboardLayout>}
