import { useEffect, useState } from "react";
import axios from "axios";
import toast from "react-hot-toast";
import DashboardLayout from "../../components/dashboard/DashboardLayout";

const API = "https://smart-society-backend-delta.vercel.app/visitor";
const config = () => ({ headers: { Authorization: `Bearer ${localStorage.getItem("token")}` } });

export default function VisitorPanel() {
  const [profile, setProfile] = useState({ name: "", email: "", phone: "" });
  const [requests, setRequests] = useState([]);
  const [flatNo, setFlatNo] = useState("");
  const [resident, setResident] = useState(null);
  const [form, setForm] = useState({ purpose: "", visitorType: "Guest", visitDate: "", visitStartTime: "", visitEndTime: "" });
  const load = async () => { try { const [p, r] = await Promise.all([axios.get(`${API}/profile`, config()), axios.get(`${API}/requests`, config())]); setProfile(p.data.data); setRequests(r.data.data || []); } catch { toast.error("Could not load visitor panel"); } };
  useEffect(() => { load(); }, []);
  const findResident = async () => { try { const r = await axios.get(`${API}/residents?flatNo=${encodeURIComponent(flatNo)}`, config()); setResident(r.data.data); } catch (e) { setResident(null); toast.error(e.response?.data?.message || "Resident not found"); } };
  const request = async (e) => { e.preventDefault(); if (!resident?.acceptingRequests) return toast.error("This resident is not accepting visitor requests"); try { const result = await axios.post(`${API}/requests`, { ...form, residentId: resident._id, visitStartTime: `${form.visitDate}T${form.visitStartTime}`, visitEndTime: `${form.visitDate}T${form.visitEndTime}` }, config()); toast.success(result.data.message); load(); } catch (err) { toast.error(err.response?.data?.message || "Request failed"); } };
  return <DashboardLayout role="visitor"><div className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-widest text-[#9b7740]">Visitor Portal</p><h1 className="text-2xl font-black text-[#32143b]">Plan your visit</h1></div><div className="grid gap-5 lg:grid-cols-2"><section className="border bg-white p-5"><h2 className="font-bold">Request a resident visit</h2><div className="mt-4 flex gap-2"><input value={flatNo} onChange={(e)=>setFlatNo(e.target.value)} placeholder="Flat number" className="h-10 flex-1 border px-3"/><button onClick={findResident} type="button" className="bg-[#32143b] px-4 text-white">Find</button></div>{resident && <p className={resident.acceptingRequests ? "mt-3 text-green-700" : "mt-3 text-red-600"}>{resident.name}, Flat {resident.flatNo}: {resident.availabilityMessage}</p>}<form onSubmit={request} className="mt-4 space-y-3"><input required placeholder="Purpose" onChange={(e)=>setForm({...form,purpose:e.target.value})} className="h-10 w-full border px-3"/><select onChange={(e)=>setForm({...form,visitorType:e.target.value})} className="h-10 w-full border px-3"><option>Guest</option><option>Delivery</option><option>Cab</option><option>Vendor</option></select><input required type="date" onChange={(e)=>setForm({...form,visitDate:e.target.value})} className="h-10 w-full border px-3"/><div className="grid grid-cols-2 gap-3"><input required type="time" onChange={(e)=>setForm({...form,visitStartTime:e.target.value})} className="h-10 border px-3"/><input required type="time" onChange={(e)=>setForm({...form,visitEndTime:e.target.value})} className="h-10 border px-3"/></div><button className="h-10 w-full bg-[#9b7740] font-bold text-white">Send request</button></form></section><section className="border bg-white p-5"><h2 className="font-bold">My profile</h2><p className="mt-4">{profile.name}</p><p className="text-sm text-[#756b78]">{profile.email}</p><p className="text-sm text-[#756b78]">{profile.phone}</p></section></div><section className="border bg-white p-5"><h2 className="font-bold">My visit requests</h2>{requests.map((item)=><div key={item._id} className="mt-3 border p-3"><b>{item.resident?.name} · Flat {item.resident?.flatNo}</b><p>{item.purpose}</p><p className="font-bold text-[#9b7740]">{item.status}{item.status === "Approved" ? ` · Gate key: ${item.gateKey}` : ""}</p></div>)}{!requests.length && <p className="mt-3 text-sm text-[#756b78]">No requests yet.</p>}</section></div></DashboardLayout>;
}
